# Generated by Django 6.0.3 on 2026-05-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=512)),
                ('full_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Farm Location',
                'verbose_name_plural': 'Farm Locations',
            },
        ),
        migrations.CreateModel(
            name='FarmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('state', models.CharField(max_length=100)),
                ('crop_type', models.CharField(max_length=100)),
                ('growth_stage', models.CharField(max_length=100)),
                ('language', models.CharField(default='english', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AgroGuard Farm Profile',
                'verbose_name_plural': 'AgroGuard Farm Profiles',
            },
        ),
        migrations.CreateModel(
            name='PestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('crop_type', models.CharField(max_length=100)),
                ('symptom_choice', models.CharField(max_length=10)),
                ('severity', models.CharField(blank=True, max_length=100)),
                ('detected_pest', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
