# Generated by Django 6.0.3 on 2026-05-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmprofile',
            name='last_field_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
