# Generated by Django 6.0.3 on 2026-05-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_farmprofile_last_field_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestreport',
            name='language',
            field=models.CharField(default='english', max_length=50),
        ),
    ]
